### ISSUE TITLE
Example cron jobs incorrect in README.md

### ISSUE THREAD

**Issue by TotalLag** [TuRz4m/Ark-docker#1]
The example you've given has the commands end in:

```
/ark/log/crontab.log 2&>1
```

But this will fail jobs because the redirect is written incorrectly.  The proper syntax is:

```
2>&1
```

**Comment by srounet** [comment]
Yeah exactly. This explain why I have a file called "1" in /ark/ folder :D
I also fixed it myself and forgot to open an issue about that.

**Comment by TuRz4m** [comment]
Sorry typo and copy/paste. I Fixed the Readme ;)
