### ISSUE TITLE
problems in setup

### ISSUE THREAD

**Issue by KasperFranz** [TuRz4m/Ark-docker#11]
Hey 

I have now tried to use your image to setup a ark server without any luck.
(this is my first try with docker) 

When trying to start the docker image ( `docker run -it -p 7779:7778 -p 7779:7778/udp -p 27016:27015 -p 27016:27015/udp -p 32331:32330 -e SESSIONNAME="Ark" -e ADMINPASSWORD="somerandompassword" -e AUTOUPDATE=120 -e AUTOBACKUP=60 -e WARNMINUTE=30 -v ~/docker-ark:/ark:Z --name ark turzam/ark`

i get the following output

> ###### 
> # Ark Server -  Wed Jul 6 13:53:00 UTC 2016
> ###### 
> 
> [Error] Can't access ark directory. Check permissions on your mapped directory with /ark

What am i doing wrong? what am i missing?

**Comment by KasperFranz** [comment]
the ark directory is created in the setup process

**Comment by KasperFranz** [comment]
I think my issue is that the default user on the docker is 1000 and my docker user is 1003. 

Do you know how to set this without having to do -u=1000 and -user=1000 on every run?

**Comment by Julime** [comment]
you need to have the right user:group permissions to yout folder:

```
julime@mymachine:/srv/docker$ ls -la
drwxr-xr-x  6 julime julime 4096 Jul  6 22:30 ark/
```

you can set these with `chmod -R julime:julime ark/`

**Comment by KasperFranz** [comment]
Julime, that doesn't solve the problem as the problem is something between the volumen on the container and my local, where permissions doesn't match up if i don't do the -u=100 etc.

**Comment by TuRz4m** [comment]
I'm working on something for you, it willl be ready soon on the 1.3-dev branch. :)

**Comment by TuRz4m** [comment]
You can try now with the following docker-compose.yml : 

> ark:
>   container_name: ark
>   image: turzam/ark:1.3-dev
>   environment:
>     - SESSIONNAME=Ark
>     - SERVERMAP=TheIsland
>     - STEAMPORT=7779
>     - SERVERPORT=27016
>     - SERVERPASSWORD="" 
>     - ADMINPASSWORD=somerandompassword
>     - BACKUPONSTART=1
>     - UPDATEONSTART=1
>     - TZ=Europe/Paris
>     - GID=1003
>     - UID=1003  
>   volumes:
>     - ~/docker-ark:/ark  
>   ports:
> - 7779:7779/udp
> - 7779:7779
> - 27016:27016/udp
> - 27016:27016
> - 32331:32330

And run it with the command `docker-compose up -d`

Note : You can't just rebind the port 7778 & 27015, you need to use the environment variable SERVERPORT and STEAMPORT (or it won't work).
Note 2 : You can see [here](https://github.com/TuRz4m/Ark-docker/blob/1.3-dev/README.md) the doc for this version (1.3-dev).

**Comment by KasperFranz** [comment]
I will try it out - thank you :)

**Comment by KasperFranz** [comment]
That didn't work sadly.

My fix was to add user 1000 to sudoer and make that account own the folder in /home/docker/docker-ark (the location of ~/docker-ark) 

I don't like the solution as user 1000 is minecraft which for security reasons wasn't in sudoers.

But I guess this is more of a general docker problem and not a problem with your docker image

**Comment by TuRz4m** [comment]
Ok, my bad : the build failed on docker hub because it couldn't contact steam... -_-
It should be good now.
Edit : don't forget to git pull turzam/ark:1.3-dev to get the latest version.

**Comment by KasperFranz** [comment]
That got it to work, I got it to work now with your updated version.

Thank you so much for all this :)

**Comment by TuRz4m** [comment]
You're welcome :]
