### ISSUE TITLE
Port Config

### ISSUE THREAD

**Issue by Julime** [TuRz4m/Ark-docker#12]
It seems like this image is somwhere only exposing tcp ports. i wanted to use docker cloud, but i cannot change the ports to udp

**Comment by TuRz4m** [comment]
You can test this with the image turzam/ark:1.3-dev :)

**Comment by TuRz4m** [comment]
Note :  the image turzam/ark:1.3-dev was not updated. It is now. Sorry. :x

**Comment by Julime** [comment]
had no time to check, and docker cloud port config was bugging around.
i will try again this weekend

**Comment by Julime** [comment]
Seems like udp port exposing is working now. 

new problem: server can't start anymore:

```
$ docker logs 6221b4245add
-su: /root/.bash_profile: Permission denied
###########################################################################
# Ark Server -  Tue Jul 12 20:22:38 UTC 2016
# UID 1000 - GID 1000
###########################################################################
No game files found. Installing...
[  WARN  ]  Your ARK server exec could not be found.
[  ERROR  ]     The ARK SavedArks directory is not writable, and saveworld will fail
Running command 'install' for instance 'main'
[  WARN  ]  Your ARK server exec could not be found.
[  ERROR  ]     The ARK SavedArks directory is not writable, and saveworld will fail
Creating the ARK server root directory (/ark/server)

$ ls -lA
insgesamt 32
-rw-r--r-- 1 julime julime 3326 Jul 12 22:36 arkmanager.cfg
drwxrwxr-x 2 julime julime 4096 Jul 12 22:36 backup
-rw-r--r-- 1 julime julime  713 Jul 12 22:36 crontab
lrwxrwxrwx 1 julime julime   52 Jul 12 22:36 Game.ini -> server/ShooterGame/Saved/Config/LinuxServer/Game.ini #broken symlink
lrwxrwxrwx 1 julime julime   64 Jul 12 22:36 GameUserSettings.ini -> server/ShooterGame/Saved/Config/LinuxServer/GameUserSettings.ini #broken symlink
drwxrwxr-x 2 julime julime 4096 Jul 12 22:36 log
drwxrwxr-x 3 julime julime 4096 Jul 12 22:36 server
drwxrwxr-x 3 julime julime 4096 Jul 12 22:36 staging
drwxrwxr-x 2 julime julime 4096 Jul 12 22:36 template
```

**Comment by TuRz4m** [comment]
Hm...  this

> [  WARN  ]  Your ARK server exec could not be found.
> [  ERROR  ]     The ARK SavedArks directory is not writable, and saveworld will fail
> Running command 'install' for instance 'main'
> [  WARN  ]  Your ARK server exec could not be found.
> [  ERROR  ]     The ARK SavedArks directory is not writable, and saveworld will fail

is because Ark Server tools checks everything in v1.5 even when you tell it to install for the first time. It's just an output problem, it's installing normally after that. (https://github.com/FezVrasta/ark-server-tools/issues/490#issuecomment-222386814)

It should work if you let the container download the game (3.6G).

I'll try to create dummy dir/files to avoid this errors.

**Comment by Julime** [comment]
works. thanks!
