### ISSUE TITLE
Incorrect version arkmanager?

### ISSUE THREAD

**Issue by Ruizman** [TuRz4m/Ark-docker#14]
root@ns313831:~# docker pull turzam/ark
Using default tag: latest
latest: Pulling from turzam/ark
Digest: sha256:49ef4e05bd025c5845a134a1b7c4d450a8f7c77008aac8374c3e2455d17cc63d
Status: Image is up to date for turzam/ark:latest
root@ns313831:~# docker exec ark arkmanager --version
Version: 1.4
Channel: master
After updating the version of the ark docker appears is the 1.4, you would not show 1.5? 

Is this correct?

**Comment by TuRz4m** [comment]
Did you recreate the container ?

**Comment by Ruizman** [comment]
As I do to recreate the container?

**Comment by TuRz4m** [comment]
If you use docker-compose, you exec `docker-compose up` and it will recreate the container with your variables and the updated image.
Or if you use the default command line you type `docker rm ark` then `docker run <all the options options....> --name ark turzam/ark` and it will recreate the container with the latest image.

If you use the same volume it should be pretty quick.
