### ISSUE TITLE
steamcmd cannot execute binary file

### ISSUE THREAD

**Issue by Bre77** [TuRz4m/Ark-docker#21]
I'm getting the following error on startup:

`/home/steam/steamcmd/steamcmd.sh: line 29: /home/steam/steamcmd/linux32/steamcmd: cannot execute binary file: Exec format error`

amd64 architecture, lib32gcc1 is installed in the container, base OS is UnRAID 6.2.4. Have successfully run an Ark server on this box before, but that was many months ago.

**Comment by Bre77** [comment]
Was an issue with my base OS not supporting 32bit binaries.

**Comment by WhiteNoseThunderPants** [comment]
I'm using Unraid 6.3.2 and having the same problem. How did you resolve it or did you run it in a VM?

**Comment by Bre77** [comment]
Unraid doesn't support 32bit binaries, so it can't run SteamCMD. I believe
It would work in an unraid VM, but I actually didn't try and ended up using
another machine.

**Comment by xiaocLoveMoney** [comment]
ubuntu 22.x too

**Comment by xiaocLoveMoney** [comment]
but i used amd cpu, idk is that problems
