### ISSUE TITLE
Permissions Denied on first run

### ISSUE THREAD

**Issue by noahrotheray** [TuRz4m/Ark-docker#36]
I am trying to perform a first run of the container using a volume, but I cant figure out why it is complaining about permissions. I've tried running it as a normal user (steam) as well as root, same issue.

See below output:

[root@localhost ~]# docker run -it -p 7778:7778 -p 7778:7778/udp -p 27015:27015 -p 27015:27015/udp -p 32330:32330 -e SESSIONNAME=myserver -e ADMINPASSWORD="mypasswordadmin" -e AUTOUPDATE=120 -e AUTOBACKUP=60 -e WARNMINUTE=30 -v /home/steam/Steam/ARK:/ark --name ark turzam/ark
chown: cannot read directory '/ark': Permission denied
###########################################################################
# Ark Server -  Fri Aug 24 11:30:00 UTC 2018
# UID 1000 - GID 1000
###########################################################################
mkdir: cannot create directory '/ark/template': Permission denied
cp: cannot create regular file '/ark/template/arkmanager.cfg': No such file or directory
cp: cannot create regular file '/ark/template/crontab': No such file or directory
cp: cannot create regular file '/ark/arkmanager.cfg': Permission denied
mkdir: cannot create directory '/ark/log': Permission denied
mkdir: cannot create directory '/ark/backup': Permission denied
mkdir: cannot create directory '/ark/staging': Permission denied
ln: failed to create symbolic link 'Game.ini': Permission denied
ln: failed to create symbolic link 'GameUserSettings.ini': Permission denied
cp: cannot stat '/ark/template/crontab': No such file or directory
No game files found. Installing...
mkdir: cannot create directory '/ark/server': Permission denied
mkdir: cannot create directory '/ark/server': Permission denied
mkdir: cannot create directory '/ark/server': Permission denied
touch: cannot touch '/ark/server/ShooterGame/Binaries/Linux/ShooterGameServer': No such file or directory
/etc/arkmanager/arkmanager.cfg: line 44: /ark/arkmanager.cfg: No such file or directory
[  WARN  ]      Your ARK server exec could not be found.
[  ERROR  ]     The ARK SavedArks directory is not writable, and saveworld will fail
[  ERROR  ]     You have not rights to write in the log directory.
Running command 'install' for instance 'main'
[  WARN  ]      Your ARK server exec could not be found.
[  ERROR  ]     The ARK SavedArks directory is not writable, and saveworld will fail
[  ERROR  ]     You have not rights to write in the log directory.
Creating the ARK server root directory (/ark/server)
mkdir: cannot create directory '/ark/server': Permission denied
 ... |^C
Session terminated, terminating shell... ...terminated.

**Comment by johan-wintgens-ap** [comment]
Here's how you resolve that: https://stackoverflow.com/a/15800917/10032060
