### ISSUE TITLE
Patch v231.9 broke startup with error while loading shared libraries: libsteam_api.so: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by TotalLag** [TuRz4m/Ark-docker#5]
```
/ark/server/ShooterGame/Binaries/Linux/ShooterGameServer: error while loading shared libraries: libsteam_api.so: cannot open shared object file: No such file or directory
```

As discussed here: https://steamcommunity.com/app/346110/discussions/0/451850468372935427/

You will need to download and place the `libsteam_api.so` file inside the container's `/usr/lib/` or `../server/ShooterGame/Binaries/Linux/`

We'll see if devs push out a hotfix since it looks like something is missing from `../server/ShooterGame/Binaries/Linux/` but if they don't, `/usr/lib/` works.

**Comment by srounet** [comment]
Can confirm that this fix is working (as a workaround).

**Comment by TuRz4m** [comment]
It seems that this is fixed now : https://steamcommunity.com/app/346110/discussions/0/451850468372935427/#c451850468373368394
You just need to update your server ^^
