### ISSUE TITLE
Ark Configs + Cores

### ISSUE THREAD

**Issue by OnstageThrower** [TuRz4m/Ark-docker#7]
Hello TuRz4m

I tried to change the Configuration file so that the game is a bit less time intensive.
That is how I got the Problem, that the Game.ini as well as the GameUsersSettings.ini configs always set to default if i restart the Container or restart the arkmanager. 
Is that normal? I testet it when I tried out the Server but the Configs are not used.

**Inputed Config:**

**Game.ini:**

LayEggIntervalMultiplier=2
GlobalSpoilingTimeMultiplier=2
EggHatchSpeedMultiplier=4
MatingIntervalMultiplier=2
CropGrowthSpeedMultiplier=2
CropDecaySpeedMultiplier=0.5

**GameUser...ini:**

[ServerSettings]
allowThirdPersonPlayer=0
AllowCaveBuildingPvE=0
alwaysNotifyPlayerJoined=1
alwaysNotifyPlayerLeft=1
bAllowFlyerCarryPvE=1
bDisableStructureDecayPvE=1
DayCycleSpeedScale=1.00000
DayTimeSpeedScale=1.00000
NightTimeSpeedScale=1.00000
DinoCharacterFoodDrainMultiplier=0.50000
DinoCharacterHealthRecoveryMultiplier=1.00000
DinoCharacterStaminaDrainMultiplier=1.00000
DinoCountMultiplier=2.00000
DinoDamageMultiplier=1.00000
DinoResistanceMultiplier=1.00000
globalVoiceChat=1
HarvestAmountMultiplier=4.00000
HarvestHealthMultiplier=1.00000
MaxStructuresInRange=6700
noTributeDownloads=1
PreventDownloadSurvivors=1
PreventDownloadItems=1
PreventDownloadDinos=1
PlayerCharacterFoodDrainMultiplier=0.20000
PlayerCharacterHealthRecoveryMultiplier=1.00000
PlayerCharacterStaminaDrainMultiplier=1.00000
PlayerCharacterWaterDrainMultiplier=0.20000
PlayerDamageMultiplier=1.00000
PlayerResistanceMultiplier=1.00000
proximityChat=0
ResourceNoReplenishRadiusPlayers=1.00000
ResourceNoReplenishRadiusStructures=1.00000
ResourcesRespawnPeriodMultiplier=1.00000
ServerAdminPassword=xxxxxx
ServerCrosshair=1
serverForceNoHud=0
serverHardcore=0
ServerPassword=xxxxxxx
serverPVE=0
ShowMapPlayerLocation=1
StructureDamageMultiplier=1.00000
StructureResistanceMultiplier=1.00000
TamedDinoDamageMultiplier=1.00000
TamedDinoResistanceMultiplier=1.00000
TamingSpeedMultiplier=8.00000
XPMultiplier=2.00000
EnablePVPGamma=1
EnablePVEGamma=1
SpectatorPassword=
DifficultyOffset=0.50000
PvEStructureDecayPeriodMultiplier=1.00000
PvEStructureDecayDestructionPeriod=1.00000
Banlist=./banlist.conf
PvPStructureDecay=0
DisableDinoDecayPvE=0
PvEDinoDecayPeriodMultiplier=1.00000
AdminLogging=1
MaxTamedDinos=8000
MaxNumbersofPlayersInTribe=2
BattleNumOfTribestoStartGame=2
TimeToCollapseROD=100
BattleAutoStartGameInterval=100
BattleSuddenDeathInterval=300
KickIdlePlayersPeriod=1800
PerPlatformMaxStructuresMultiplier=1.00000
StructureDamageRepairCooldown=0
bForceAllStructureLocking=1
AutoDestroyOldStructuresMultiplier=0.00000
bUseVSync=0
MaxPlatformSaddleStructureLimit=100
bPassiveDefensesDamageRiderlessDinos=1
[/script/engine.gamesession]
MaxPlayers=20
[SessionSettings]
SessionName=xxxxxxxxx
[MessageOfTheDay]
Duration=5
Message=

**After the Server rebooted:**

[ServerSettings]
ServerPassword=xxxxxxxx
ServerAdminPassword=xxxxxxx
RCONEnabled=True
RCONPort=32330
PvEDinoDecayPeriodMultiplier=1.000000
KickIdlePlayersPeriod=2400.000000
PerPlatformMaxStructuresMultiplier=1.000000
AutoSavePeriodMinutes=15.000000
ListenServerTetherDistanceMultiplier=1.000000
MaxTamedDinos=5000.000000
RCONServerGameLogBuffer=600.000000

[/Script/ShooterGame.ShooterGameUserSettings]
MasterAudioVolume=1.000000
MusicAudioVolume=1.000000
SFXAudioVolume=1.000000
VoiceAudioVolume=1.000000
CameraShakeScale=1.000000
bFirstPersonRiding=False
bThirdPersonPlayer=False
bShowStatusNotificationMessages=True
TrueSkyQuality=0.000000
FOVMultiplier=1.000000
GroundClutterDensity=0.000000
bFilmGrain=False
bMotionBlur=False
bUseDFAO=False
bUseSSAO=False
bShowChatBox=True
bCameraViewBob=True
bInvertLookY=False
bFloatingNames=True
bChatBubbles=True
bHideServerInfo=False
bJoinNotifications=False
bCraftablesShowAllItems=True
bLocalInventoryShowAllItems=False
bRemoteInventoryShowAllItems=False
LookLeftRightSensitivity=1.000000
LookUpDownSensitivity=1.000000
GraphicsQuality=1
ActiveLingeringWorldTiles=6
ClientNetQuality=3
LastServerSearchType=0
LastServerSearchHideFull=False
LastServerSearchProtected=False
HideItemTextOverlay=False
bDistanceFieldShadowing=False
LODScalar=0.780000
bToggleToTalk=False
HighQualityMaterials=True
HighQualitySurfaces=True
bTemperatureF=False
bDisableTorporEffect=False
bChatShowSteamName=False
bChatShowTribeName=True
EmoteKeyBind1=0
EmoteKeyBind2=0
bNoBloodEffects=False
bLowQualityVFX=False
bSpectatorManualFloatingNames=False
bSuppressAdminIcon=False
bUseSimpleDistanceMovement=False
bUseVSync=False
MacroCtrl0=
MacroCtrl1=
MacroCtrl2=
MacroCtrl3=
MacroCtrl4=
MacroCtrl5=
MacroCtrl6=
MacroCtrl7=
MacroCtrl8=
MacroCtrl9=
ResolutionSizeX=1280
ResolutionSizeY=720
LastUserConfirmedResolutionSizeX=1280
LastUserConfirmedResolutionSizeY=720
WindowPosX=-1
WindowPosY=-1
bUseDesktopResolutionForFullscreen=False
FullscreenMode=2
LastConfirmedFullscreenMode=2
Version=5

[ScalabilityGroups]
sg.ResolutionQuality=100
sg.ViewDistanceQuality=3
sg.AntiAliasingQuality=3
sg.ShadowQuality=3
sg.PostProcessQuality=3
sg.TextureQuality=3
sg.EffectsQuality=3
sg.TrueSkyQuality=3
sg.GroundClutterQuality=3
sg.IBLQuality=1
sg.HeightFieldShadowQuality=3

[SessionSettings]
SessionName=xxxxxxxxx

[/Script/Engine.GameSession]
MaxPlayers=70

Do you know what might be the issue? Have I done something wrong?

Plus everytime we reboot the System, the System creates a Core file, which is around 800 MB large. This starts up filling up our Server. Do you know what we could do, to stop that or to automate the deleating of the Core files, that our Server doen't grow too rapidly?

Thank you very much for you help

OnstageThrower

**Comment by TuRz4m** [comment]
Hello,
A few question : 
How do you run your container (which command) ? 
Which files do you modify (the path) ? _/ShooterGame/Saved/Config/LinuxServer/Game.ini_ ? the symbolic link ?

_Maybe_ Ark detects that the ini files are corrupted and recreates them... Try to change a small value like **MaxTamedDinos** to _5001.000000_ to see if it's overwritten again.

**Comment by OnstageThrower** [comment]
Hello TuRz4m

We used the comand to create the container:
docker run -it -p xxx.xxx.xxx.xxx:7778:7778 -p xxx.xxx.xxx.xxx:7778:7778/udp -p xxx.xxx.xxx.xxx:27015:27015 -p xxx.xxx.xxx.xxx:27015:27015/udp -p xxx.xxx.xxx.xxx:32330:32330 -e SESSIONNAME="xxxxxxxx" -e ADMINPASSWORD="xxxxxxxx" -e BACKUPONSTART=0 -e TZ="Europe/Zurich" -v /mnt/docker-data/ark:/ark -m 12G --memory-reservation 6G --name ark-private turzam/ark

**Container**
Start
docker start ark-private

Stop
docker stop ark-private

Restart
docker restart ark-private

**Ark server**
Start
docker exec ark-private arkmanager start

Stop
docker exec ark-private arkmanager stop

Restart
docker exec ark-private arkmanager restart

and to Edit the Config files i used the symbolic link the Paths are: 
Path Game.ini: server/ShooterGame/Saved/Config/LinuxServer/Game.ini
Path GameUserSettings.ini: server/ShooterGame/Saved/Config/LinuxServer/GameUserSettings.ini

It overwrites everything exept the password and the session name

Thx a lot

OnstageThrower

**Comment by TuRz4m** [comment]
Sorry, i was pretty busy working yesterday.
But I tried with your examples and if I don't start my Game.ini file with _[script/shootergame.shootergamemode]_, the ark server erases all the configuration files when it starts.
Can you try putting this in your Game.ini : 

> [script/shootergame.shootergamemode]
> LayEggIntervalMultiplier=2
> GlobalSpoilingTimeMultiplier=2
> EggHatchSpeedMultiplier=4
> MatingIntervalMultiplier=2
> CropGrowthSpeedMultiplier=2
> CropDecaySpeedMultiplier=0.5

without touching the GameUserSettings.ini ?

**Comment by OnstageThrower** [comment]
Hi TuRz4m

I just tried that and it works. It has something to do with the top part [script/shootergame.shootergamemode]
that is what i found out.
It only works if it is written as well.

Do you know by any chance if I wrote something wrong in my configs in the GameUserSettings? 
Now the Game.ini works but I am not sure if the GameUserSettings work cause I haven't had the chance to test in in game.

Or is it possible to change everything in the Game.ini configs?

Thx a lot

OnstageThrower

**Comment by TuRz4m** [comment]
I just tried your GameUserSettings and it doesn't work.
But you can generate a correct one here : http://ini.arkforum.de/

**Comment by OnstageThrower** [comment]
ok I'll try
thx for all the help so far

**Comment by OnstageThrower** [comment]
Hello TuRz4m

I finaly had time to test it properly and i found out, that now the configs dont deleate, but aren't working.
If i change the harvest amount to 4 i don't pick up 4 stones only one.
Do you know what to do?
and may i have your configs to test it?

Thanks a lot

OnstageThrower

**Comment by TuRz4m** [comment]
> [ServerSettings]
> HarvestAmountMultiplier=4  

Do you have something like that in your GameUserSettings.ini  ?

**Comment by OnstageThrower** [comment]
Hi TuRz4m

I was finaly able to fix it.
The Gererated File doesn't work with the Configs of ARK so i took the changes i wanted to do out of the File and inserted it into the [ServerSettings] and it suddenly worked.
I am still ajusting it bit by bit, but it finaly works.
Sorry for ansering you so late, but i tested it recently and forgot to write you back.

Just one more question. Do you know what I can do to stop it from Generating core.xxxxx files? Or do you know how to deleate them with a script without doing it manuly?

Thanks a lot

OnstageThrower

**Comment by TuRz4m** [comment]
I think the core.xxxx are created when your game crash. You can try `ulimit -c 0` to turn them off.

**Comment by OnstageThrower** [comment]
Hi TuRz4m

I just found out, that the server generates corefiles if i restart the arkmanager as well.
Even thought the docker container force reboot isn't activated, it can't be, that it crashes every secound day once. 
I got core files from every second day

Thx a lot

OnstageThrower

**Comment by OnstageThrower** [comment]
Hi TuRz4m

I realized, that it always kills the server after 30 seconds if the server hasn,t stopped jet.
Do you know what to do, to make it stop killing the server when stopping?

`docker exec ark-private arkmanager restart`
Stopping server...
**Killing server...**
The server has been stopped
The server is starting...
The server is now up

Thanks a lot dude

OnstageThrower
