### ISSUE TITLE
Cannot change maxplayers value

### ISSUE THREAD

**Issue by RobinVanCauter** [TuRz4m/Ark-docker#9]
Hi,

For some reason I am unable to set the amount of max players, my GameUserInfo.ini file defaults to 70 players on server startup.

**Comment by TuRz4m** [comment]
Hi,
By default the arkmanager.cfg will override your gameusersettings.
Delete or change this line : "ark_MaxPlayers=${NBPLAYERS}" in the arkmanager.cfg and see if it works.

However, if your GameUserSettings.ini is  overwritten every time your start your server, it may be because your config file has a bad format. (see [here](https://github.com/TuRz4m/Ark-docker/issues/7))

**Comment by RobinVanCauter** [comment]
Yeah I saw the arkmanager file and commented out the line, but it still started using 70 players. I'll have another look at it later and keep you posted if I managed to fix it :) Thanks for the quick response!

EDIT:

So I checked again, in the arkmanager.cfg file the MaxPlayers line is commented out. And when I change my GameUserSettings.ini file at the bottom to say for example MaxPlayers=20 it just changes the value to 70 on startup again.

I have a bunch of other custom settings at the top which are left unchanged and work perfectly.

**Comment by TuRz4m** [comment]
Did you put it after [/Script/Engine.GameSession] ?
Like this ?

> [/Script/Engine.GameSession]
> MaxPlayers=20    

Or if you put `ark_MaxPlayers=20` in arkmanager.cfg, it should override your config file (it's directly put in the command line).

**Comment by RobinVanCauter** [comment]
This what our GameUserSettings.ini looks like after starting the server (only change after launch is the value 20 that changed into 70 for some reason.)

As you can see all of our other settings are left unchanged and used by the server.

```
[ServerSettings]
ServerMap=TheIsland
ServerPassword=420blazeit
ServerAdminPassword=chillbits2012
RCONEnabled=True
RCONPort=32330
PvEDinoDecayPeriodMultiplier=1.000000
KickIdlePlayersPeriod=2400.000000
PerPlatformMaxStructuresMultiplier=1.000000
AutoSavePeriodMinutes=15.000000
ListenServerTetherDistanceMultiplier=1.000000
MaxTamedDinos=5000.000000
RCONServerGameLogBuffer=600.000000
alwaysNotifyPlayerJoined=True
alwaysNotifyPlayerLeft=True
allowThirdPersonPlayer=True
ShowMapPlayerLocation=True
noTributeDownloads=True
DisableStructureDecayPvE=True
DisableDinoDecayPvE=True
AllowFlyerCarryPvE=True
NightTimeSpeedScale=0.9
TamingSpeedMultiplier=3.0
HarvestAmountMultiplier=2.5
HarvestHealthMultiplier=2.0
AllowCaveBuildingPvE=true
PvPStructureDecay=True

... Some generated stuff in between ...

[SessionSettings]
SessionName=Arkitects

[/Script/Engine.GameSession]
MaxPlayers=70
```

I'll try the arkmanager.cfg trick you just mentioned in a minute.

**Comment by RobinVanCauter** [comment]
Alright, setting it manually in the arkmanager.cfg file works! Thanks :)
